language: c
sudo: false

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - ulimit -n 2048

matrix:
  include:
    - env: GHCVER=7.10.2
      addons: {apt: {packages: [ghc-7.10.2],sources: [hvr-ghc]}}

install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test
